version: '3.1'

services:

 reactapp:
         image: reactapp:v1
         container_name: reactapp
         ports:
                 - 80:3000
         volumes:
                 - '.:/app'
                 - '/app/node_modules'
         environment:
                 - CHOKIDAR_USEPOLLING=true
