version: '3.1'

services:

  sample:
    container_name: reactapp
    image: react_dev:v1
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 80:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
